AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Queue and lambda for sending SMS messages

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - test
    Description: Environment for deploy

Mappings:
  EnvironmentMap:
    prod:
      project: sms-queue-service
    test:
      project: sms-queue-service-test

Resources:
  SimpleQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: true
      FifoQueue: true
      KmsMasterKeyId: alias/aws/sqs
      MessageRetentionPeriod: 1209600 # 14 days
      Tags:
        - Key: 'created-by'
          Value: 'sms-queue-service'
        - Key: 'created-for'
          Value: 'dbowland'
        - Key: 'environment'
          Value: !Ref Environment
      VisibilityTimeout: 60

  SQSPayloadProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Description: Processes queued messages to send sms messages.
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Handler: handlers/sqs-payload-processor.sqsPayloadProcessorHandler
      CodeUri: './dist'
      Environment:
        Variables:
          PROJECT_ID: !Ref PinpointApplication
          SMS_FROM: '+18449163034'
          SMS_REGION: us-east-1
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            BatchSize: 7
            Queue: !GetAtt SimpleQueue.Arn
      MemorySize: 128
      Timeout: 60
      Policies:
        # Give Lambda basic execution Permission
        - AWSLambdaBasicExecutionRole
        # Grant access to SQS queue
        - SQSPollerPolicy:
            QueueName: !GetAtt SimpleQueue.QueueName
        # Access to send messages thru Pinpoint
        - Version: 2012-10-17
          Statement:
            - Action:
                - 'mobiletargeting:Send*'
              Effect: Allow
              Resource: !Sub
                - 'arn:aws:mobiletargeting:us-east-1:${AWS::AccountId}:apps/${ProjectId}/messages'
                - ProjectId: !Ref PinpointApplication
      Tags:
        'created-by': 'sms-queue-service'
        'created-for': 'dbowland'
        'environment': !Ref Environment

  PinpointApplication:
    Type: AWS::Pinpoint::App
    Properties:
      Name: !FindInMap [EnvironmentMap, !Ref Environment, project]
      Tags:
        'created-by': 'sms-queue-service'
        'created-for': 'dbowland'
        'environment': !Ref Environment

  PinpointSms:
    Type: AWS::Pinpoint::SMSChannel
    Properties:
      ApplicationId: !Ref PinpointApplication
      Enabled: true

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: [SQSPayloadProcessor]
    Properties:
      LogGroupName: !Sub /aws/lambda/${SQSPayloadProcessor}
      RetentionInDays: 30
      Tags:
        - Key: 'created-by'
          Value: 'sms-queue-service'
        - Key: 'created-for'
          Value: 'dbowland'
        - Key: 'environment'
          Value: !Ref Environment
